name: Terraform workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest

    env:
      AWS_ID: ${{ secrets.AWS_ID }}
      AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}

    steps:
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Checkout repository
        uses: actions/checkout@v4
