on:
  push:
    branches:
      - staging

jobs:
  terrascan_job:
    runs-on: ubuntu-latest
     name: terrascan
     steps:
     - name: Checkout repository
       uses: actions/checkout@v4
     - name: Run Terrascan
       uses:
       id: terrascan
       with:
        iac_type: terraform
        